sesion_04/tweets/urls.py
"""Tweets app URL config"""

from django.urls import path

from . import views


app_name = "tweets"
urlpatterns = [
    path("", views.TweetListView.as_view(), name="list"),
    path("create", views.CreateTweetView.as_view(), name="create"),
]

sesion_04/twitter/urls.py
"""Twitter URL Configuration"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("tweets/", include("tweets.urls")),
]

sesion_04/users/urls.py
"""Users app URLS"""

from django.urls import path

from . import views


app_name = "users"
urlpatterns = [
    # Function Based Views
    # path("login", views.users_login, name="login"),
    # path("logout", views.users_logout, name="logout"),
    # path("signup", views.sign_up, name="signup"),
    # path("me", views.profile, name="profile"),

    # Class based views
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.LogoutView.as_view(), name="logout"),
    path("signup", views.SignupView.as_view(), name="signup"),
    path("me", views.ProfileView.as_view(), name="profile"),
]

sesion_04/tweets/models.py
"""Tweets app models"""

from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class Tweet(models.Model):
    """Tweet model"""
    content = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String representation of a tweet"""
        return self.content

sesion_04/tweets/forms.py
"""Tweets app forms"""

from django import forms

from .models import Tweet


class TweetModelForm(forms.ModelForm):
    """Tweet model form"""
    class Meta:
        model = Tweet
        fields = ['content']

sesion_04/users/forms.py
"""Users app forms"""

from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class UserForm(forms.Form):
    """User form"""
    username = forms.CharField()
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirmation = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        """Checks if username is unique"""
        username = self.cleaned_data.get('username')
        username_exists = User.objects.filter(username=username).exists()

        if username_exists:
            raise forms.ValidationError("Este username ya está en uso")

        return username

    def clean(self):
        """Checks if passwords matches"""
        data = self.cleaned_data
        password = data.get('password')
        password_confirmation = data.get('password_confirmation')

        if password != password_confirmation:
            raise forms.ValidationError("Las contraseñas no coinciden")

        return data

    def save(self):
        """Creates a new user"""
        data = self.cleaned_data
        data.pop('password_confirmation')  # Elimina la llave de un diccionario
        return User.objects.create_user(**data)  # Spread operator

sesion_04/tweets/views.py
"""Tweets app views"""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, ListView
from django.urls import reverse_lazy

from .forms import TweetModelForm
from .models import Tweet


class TweetListView(ListView):
    """Shows all tweets"""
    queryset = Tweet.objects.all()
    template_name = "../templates/tweets/list.html"


class CreateTweetView(LoginRequiredMixin, FormView):
    """Creates a new tweet"""
    form_class = TweetModelForm
    template_name = "../templates/tweets/create.html"
    success_url = reverse_lazy("users:profile")

    def form_valid(self, form):
        tweet = form.save(commit=False)
        tweet.user = self.request.user
        tweet.save()
        return super().form_valid(form)

sesion_04/users/views.py
"""Users app views"""

# Standard library imports
# import os

# Django imports
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView

# Third-party libraries
# import requests
# import restframework

# Local imports
from tweets.models import Tweet
from .forms import UserForm


# Class based views


class LoginView(auth_views.LoginView):
    """Authenticates a user"""
    template_name = "../templates/users/login.html"
    redirect_authenticated_user = True


class ProfileView(LoginRequiredMixin, TemplateView):
    """Shows user's profile"""
    template_name = "../templates/users/profile.html"

    def get_context_data(self):
        """Puts tweets in context"""
        context = super().get_context_data()
        tweets = Tweet.objects.filter(user=self.request.user)
        context['tweets'] = tweets
        return context


class LogoutView(auth_views.LogoutView):
    """Logs out a user"""


class SignupView(FormView):
    """Register a user"""
    form_class = UserForm
    success_url = reverse_lazy("users:profile")
    template_name = "../templates/users/signup.html"

    def form_valid(self, form):
        """Saves a user"""
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


# Function based views

def users_login(request):
    """Authenticates a user"""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect("users:profile")
    return render(request, "../templates/users/login.html")


@login_required
def profile(request):
    """Shows user's profile"""
    return render(request, "../templates/users/profile.html")


@login_required
def users_logout(request):
    """Log out a user"""
    logout(request)
    return redirect("users:login")


def sign_up(request):
    """Creates a new user"""
    form = UserForm()

    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("users:profile")

    return render(request, "../templates/users/signup.html", {"form": form})

sesion_04/templates/tweets/create.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Crear Tweet</title>
</head>
<body>
    <h1>Crear tweet</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Crear</button>
    </form>
</body>
</html>

sesion_04/templates/tweets/list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Tweets</title>
</head>
<body>
    <section>
        <h1>Últimas noticias</h1>

        {% for tweet in object_list %}
        <article>
        <p>{{ tweet.content }}</p>
        <p><strong>@{{ tweet.user.username }}</strong></p>
        <p><small><i>{{ tweet.created_at }}</i></small></p>
        <hr />
        </article>
        {% endfor %}

    </section>
</body>
</html>

sesion_04/templates/users/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Iniciar sesión</title>
</head>
<body>
    <h1>Iniciar sesión</h1>

    <form method="post">
        {% csrf_token %}
        <p>
            <label for="username-id">Usuario:</label>
            <input type="text" name="username" id="username-id">
        </p>

        <p>
            <label for="password-id">Contraseña:</label>
            <input type="password" name="password" id="password-id">
        </p>

        <button type="submit">Enviar</button>
    </form>
</body>
</html>

sesion_04/templates/users/profile.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
</head>
<body>
    <h1>@{{ request.user.username }}</h1>

    {% with request.user as user %}
        <ul>
            <li>{{ user.first_name }}</li>
            <li>{{ user.last_name }}</li>
            <li>{{ user.email }}</li>
        </ul>
    {% endwith %}

    <section>
        <h2>Tweets</h2>

        {% for tweet in tweets %}
            <article>
                <p>{{ tweet.content }}</p>
                <p>
                    <i>
                        <small>
                            {{ tweet.created_at }}
                        </small>
                    </i>
                </p>
            </article>
            <hr />
        {% endfor %}
    </section>


    <a href="{% url 'users:logout' %}">Cerrar sesión</a>
</body>
</html>

sesion_04/templates/users/signup.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Registro</title>
</head>
<body>
    <h1>Registro</h1>

    <div>
        {% for error in form.non_field_errors %}
            <p>
                <small>
                    {{ error }}
                </small>
            </p>
        {% endfor %}
    </div>

    <form method="post">
        {% csrf_token %}
        <p>
            <label for="username-id">Nombre de usuario</label>
            <input type="text" name="username" id="username-id" {% if form.errors %}value="{{ form.username.value }}"{% endif %} />
            {% for error in form.username.errors %}
                <p>
                    <small>
                        {{ error }}
                    </small>
                </p>
            {% endfor %}
        </p>

        <p>
            <label for="email-id">Correo electrónico</label>
            <input type="email" name="email" id="email-id"/>
            {% for error in form.email.errors %}
                <p>
                    <small>
                        {{ error }}
                    </small>
                </p>
            {% endfor %}
        </p>

        <p>
            <label for="first-name-id">Nombre(s)</label>
            <input type="text" name="first_name" id="first-name-id"/>

            {% for error in form.first_name.errors %}
                <p>
                    <small>
                        {{ error }}
                    </small>
                </p>
            {% endfor %}

        </p>

        <p>
            <label for="last-name-id">Apellido(s)</label>
            <input type="text" name="last_name" id="last-name-id"/>

            {% for error in form.last_name.errors %}
                <p>
                    <small>
                        {{ error }}
                    </small>
                </p>
            {% endfor %}
        </p>

        <p>
            <label for="password-id">Contraseña</label>
            <input type="password" name="password" id="password-id"/>

            {% for error in form.password.errors %}
                <p>
                    <small>
                        {{ error }}
                    </small>
                </p>
            {% endfor %}
        </p>

        <p>
            <label for="password-confirmation-id">Confirmar contraseña</label>
            <input type="password" name="password_confirmation" id="password-confirmation-id"/>

            {% for error in form.password_confirmation.errors %}
                <p>
                    <small>
                        {{ error }}
                    </small>
                </p>
            {% endfor %}
        </p>
        <button type="submit">Crear usuario</button>
    </form>
</body>
</html>

sesion_04/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Iniciar sesión</title>
</head>
<body>
    <h1>Iniciar sesión</h1>

    <form method="post">
        {% csrf_token %}
        <p>
            <label for="username-id">Usuario:</label>
            <input type="text" name="username" id="username-id">
        </p>

        <p>
            <label for="password-id">Contraseña:</label>
            <input type="password" name="password" id="password-id">
        </p>

        <button type="submit">Enviar</button>
    </form>
</body>
</html>