sesion_02/bank/urls.py
"""Bank URL Configuration"""

from django.urls import path, include

urlpatterns = [
    path('food/', include('food.urls')),
]

sesion_02/food/urls.py
"""Food app URL config"""

from django.urls import path

from .views import list_food, detail_food, create_food

app_name = 'food'
urlpatterns = [
    path('', list_food, name='list'),
    path('<int:id>', detail_food, name='detail'),
    path('create', create_food, name='create'),
]

sesion_02/food/views.py
"""Food app views"""

from django.shortcuts import render, redirect


food = []


def list_food(request):
    """Return a list of food"""
    context = {
        "food": food
    }

    return render(request, "list.html", context)


def detail_food(request, id):
    """Return a detail of food"""
    context = {
        "food": food[int(id)]
    }

    return render(request, "detail.html", context)


def create_food(request):
    """Create a food"""
    if request.method == 'POST':
        name = request.POST['name']
        food.append(name)
        return redirect('food:list')

    return render(request, "create.html")

sesion_02/food/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  {% block title %}
  <title>App de Comida</title>
  {% endblock title %}
</head>
<body>
  {% block content %}{% endblock content %}
</body>
</html>

sesion_02/food/templates/create.html
{% extends 'base.html' %}

{% block content %}
<h1>Crear nuevo alimento</h1>

<form action="{% url 'food:create' %}" method="POST">
  {% csrf_token %}
  <p>
    <label for="name-id">Nombre:</label>
    <input type="text" name="name" id="name-id" />
  </p>
  <button type="submit">Crear</button>
</form>
{% endblock content %}

sesion_02/food/templates/detail.html
{% extends "base.html" %}

{% block title %}
<title>Detalle de {{ food }}</title>
{% endblock %}

{% block content %}
<h1>Detalle de {{ food }}</h1>

<a href="{% url 'food:list' %}">Volver</a>

{% endblock content %}

sesion_02/food/templates/list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="title">Comida favorita</h1>
  <a href="{% url 'food:create' %}">Crear nuevo</a>
  {% if food %}
    <ul>
      {% for item in food %}
      <li>{{ item }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No hay comida</p>
  {% endif %}
  <a href="{% url 'food:detail' 1 %}">Ir a detalle de Sushi </a>
{% endblock content %}